package com.parasoft.examples.model.jpa;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

public class HsqlDbUtil
{
    private HsqlDbUtil()
    {
        // static util methods only
    }

    public static Connection getConnection()
        throws Exception
    {
        Class.forName("org.h2.Driver");
        return DriverManager.getConnection("jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=2");
    }

    public static void initialize(Connection conn)
        throws Exception
    {
        Statement stmt = conn.createStatement();
        stmt.execute("DROP TABLE AUTOMOBILES IF EXISTS");
        stmt.execute("CREATE TABLE AUTOMOBILES ("
                + " ID BIGINT generated by default as identity not null,"
                + " MAKE VARCHAR(32),"
                + " MODEL VARCHAR(32),"
                + " COLOR VARCHAR(32),"
                + " MILEAGE INT,"
                + " CONSTRAINT PK PRIMARY KEY(ID)"
                + ")");
    }
}
